#In this notebook we're going to cover some of the more fundamental concepts of tensors using Tensorflow

More specifically we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try out for yourself!

##Introduction to tensors

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
#Create tensors with tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [3]:
#Check number of dimensions of a tensor (ndims stand for number of dimensions)
scalar.ndim

0

In [4]:
vector = tf.constant([10,11])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
from numpy import float16
#Create another matrix
anotherMatrix = tf.constant([[10.,7.],
                      [7.,10.],
                      [10.,11.]], dtype=float16) #specify datatype 

In [9]:
anotherMatrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]]
                      )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:
* Scalar:a single number
* Vector:a number with a direction
* Matrix:a 2-dimensional array of numbers
* Tensor:an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector etc...)

In [12]:
#Create the same tensor with tf.variable as 

changeableTensor = tf.Variable([10,7])
constantTensor = tf.constant([10,7])

changeableTensor, constantTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
changeableTensor[1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

### Creating random tensors

In [14]:
#Creating 2 random but the same tensor
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(7)
random2 = random2.normal(shape=(3,2))

random1, random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [15]:
#Shuffle a tensor (Valuable for when you want to shuffle your data so the inherent order is lost)

notShuffled = tf.constant([[10,7],
                           [9,6],
                           [11,8]])
notShuffled.ndim

#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(notShuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 9,  6],
       [11,  8]], dtype=int32)>

> if both global and operation level seed are set: Both seeds are used in conjunction to determine the random sequence

In [16]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
import numpy as np

numpyA = np.arange(1,25,dtype = np.int32)
numpyA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpyA)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [20]:
Arranged = tf.constant(numpyA, shape = (2,3,4))
NonArranged = tf.constant(numpyA)
Arranged, NonArranged

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting information from tensors

When dealing with tensors you want to be aware of these attributes

* shape
* rank
* axis or dimension
* size


In [21]:
#Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
2 * 3 * 4 * 5

120

In [25]:
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of our tensor:",  rank_4_tensor.shape)
print("Elements across the 0 axis", rank_4_tensor.shape[-1])
print("Total elements in our tensor", tf.size(rank_4_tensor))
print("Total elements in our tensor", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of our tensor: (2, 3, 4, 5)
Elements across the 0 axis 5
Total elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total elements in our tensor 120


###Indexing Tensors

Tensors can be indexed just like python list

In [26]:
#Get the first 2 elements of each dimension
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [27]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
#GEt the first element from each dimension from each index except the second to last: 1
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [29]:
#GEt the first element from each dimension from each index except the final 1
rank_4_tensor[:1, :1, :1, ]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
#Create a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],[1,2]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [31]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2], dtype=int32)>

In [32]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [33]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [34]:
#expand the 0 axis
tf.expand_dims(rank_2_tensor, axis=0) #-1 means expand the final axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 1,  2]]], dtype=int32)>

### Manipulating tensor (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [35]:
#Basic operations
tensor = tf.constant([[10,7],
                      [1,2]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [11, 12]], dtype=int32)>

In [36]:
#Original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [37]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 10,  20]], dtype=int32)>

In [38]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-9, -8]], dtype=int32)>

In [39]:
#We can use the tensorflow builtin methods
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 10,  20]], dtype=int32)>

**Matrix multiplication**

In machine learning tensor multiplication is one of the ms common operations

There are 2 rules out tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer dimensions 

In [40]:
#Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[107,  84],
       [ 12,  11]], dtype=int32)>

In [41]:
#Matrix multiplication with python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[107,  84],
       [ 12,  11]], dtype=int32)>

In [42]:
#Create a (3,2) tensor
X = tf.constant([[1,2],
                [2,3],
                [3,4]])

#Create another (3,2) tensor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [43]:
#Need to reshape so Y is in proper dimensions to do matrix multiplication
X @ tf.reshape(Y, (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [44, 49, 54],
       [61, 68, 75]], dtype=int32)>

In [44]:
tf.matmul(X,tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [44, 49, 54],
       [61, 68, 75]], dtype=int32)>

In [45]:
tf.reshape(X, (2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 47,  52],
       [ 92, 102]], dtype=int32)>

In [46]:
#Change X instead of Y
tf.matmul(tf.reshape(X, (2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 47,  52],
       [ 92, 102]], dtype=int32)>

In [47]:
#Can do same shape change as transpose (For this case)
X, tf.transpose(X), Y, tf.transpose(Y)

#tf. transpose shifts elements across diagonal axis of matrix

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [48]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 29, 35],
       [38, 48, 58],
       [53, 67, 81]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using:
* `tf.matmul`
* `tf.tensordot()`

In [49]:
#Perform dot product on X and Y requires X or Y to be transposed
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[58, 64],
       [85, 94]], dtype=int32)>

In [50]:
#Perform matrix multiplication on X and Y (transposed)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[23, 29, 35],
       [38, 48, 58],
       [53, 67, 81]], dtype=int32)>

In [51]:
#Perform matrix multiplication on X and Y (reshaped)
tf.tensordot(X, tf.reshape(Y, (2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [44, 49, 54],
       [61, 68, 75]], dtype=int32)>

In [52]:
#Check values of Y, reshape Y and transposed Y

print("Normal Y:")
print(Y, "\n")

print("reshape Y:")
print(tf.transpose(Y), "\n")

print("transposed Y:")
print(tf.reshape(Y, (2,3)), "\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

reshape Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 

transposed Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 



### Changing datatype of a tensor

In [53]:
B = tf.constant([1.7, 5.1])
B.dtype

tf.float32

In [54]:
C = tf.constant([2,3])
C.dtype

tf.int32

In [55]:
#change from float32 to float16 lower precision (however faster on modern GPUs and CPUs)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 5.1], dtype=float16)>

In [56]:
#Change from int32 to int 16
E = tf.cast(C, dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 3], dtype=int16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values 

In [57]:
#Getting the absolute values
F = tf.constant([-6,-9])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-6, -9], dtype=int32)>

In [58]:
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>

Let's go through the following forms of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [59]:
#Create a random tensor
G = tf.random.Generator.from_seed(7)
G = G.normal(shape=(5,5,5), mean=4, stddev=8)
G

<tf.Tensor: shape=(5, 5, 5), dtype=float32, numpy=
array([[[ -6.5923166 ,   6.3028536 ,  -3.006321  ,   3.2914386 ,
           9.536932  ],
        [ 10.737257  ,   3.4897203 ,  11.424063  ,  -0.831831  ,
           2.5864584 ],
        [  4.3376827 ,   6.323037  ,   1.6316428 ,   2.3092635 ,
           4.08504   ],
        [ 16.132318  ,   6.184459  ,   1.6059489 ,   1.07814   ,
           8.9506645 ],
        [ -4.1046524 ,   6.263337  ,  13.705788  ,   7.759118  ,
           7.0355463 ]],

       [[ -1.3312206 ,   8.843677  ,   5.534494  ,  10.436662  ,
           7.815241  ],
        [ -2.249699  ,  -3.9751282 ,   6.651998  ,  -0.35620308,
          16.178005  ],
        [  8.744257  ,  -1.0807419 ,   6.9628525 ,  -4.7517776 ,
           0.31884384],
        [ 16.336405  ,   2.6541955 ,   0.48730803,   0.6966057 ,
           6.870179  ],
        [-11.276715  ,   2.324185  ,  10.628974  ,   3.4643943 ,
           1.1915572 ]],

       [[ 12.707267  ,  -7.090452  ,  11.044106  ,  -9.

In [60]:
#Find the minimum of the tensor
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=float32, numpy=-17.882263>

In [61]:
#Find the maximum of the tensor
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=26.264513>

In [62]:
#Find the mean of the tensor
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=float32, numpy=4.3101387>

In [63]:
#Find the sum of the tensor
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=float32, numpy=538.76733>

In [64]:
#Find the variance
tf.math.reduce_variance(G)

<tf.Tensor: shape=(), dtype=float32, numpy=59.543713>

In [65]:
#find the standard deviation
tf.math.reduce_std(G)

<tf.Tensor: shape=(), dtype=float32, numpy=7.7164574>

### Finding the positional maximum and minimum

In [66]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
H = tf.random.uniform(shape = [50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [67]:
#Find maximum value in the tensor (!argmax returns the index of the max value)
H[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.6645621>

In [68]:
#Find minimum value in the tensor
H[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.44100678>

In [69]:
tf.reduce_mean(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.513808>

###Squeezing a tensor

In [70]:
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,50))
I

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [71]:
I.shape

TensorShape([1, 1, 1, 50])

In [72]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One hot encoding tensors

In [73]:
#Create a list of indices
some_list = [0, 1, 2, 3, 4]
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [74]:
tf.one_hot(some_list, depth=5, on_value="on", off_value="off")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off', b'off'],
       [b'off', b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'off', b'on']], dtype=object)>

### Squaring, log, square root

In [75]:
J = tf.range(1,10)
J 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [77]:
tf.sqrt(tf.cast(J, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [78]:
tf.math.log(tf.cast(J,tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and NumPy

In [79]:
#Create a tensor directly from a numpy array
K = tf.constant(np.array([3.,4.,5.,6.]))
K

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([3., 4., 5., 6.])>

In [80]:
#Convert a tensor back to a numpy array

In [81]:
np.array(K), type(np.array(K))

(array([3., 4., 5., 6.]), numpy.ndarray)

In [82]:
K.numpy(), type(K.numpy())

(array([3., 4., 5., 6.]), numpy.ndarray)

In [83]:
numpy_K = tf.constant(np.array([3., 4., 5., 6.]))
tensor_K = tf.constant([3., 4., 5., 6.])

#Checking d_Types
numpy_K.dtype, tensor_K.dtype

(tf.float64, tf.float32)

### Finding access to gpus

In [84]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [85]:
!nvidia-smi

Sun Mar 27 15:37:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0    26W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note as gpu is used as the runtime environment the GPU is automatically used**